"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$@+jmpv&75(*^h-l07s8a_a$1hk$fnoz+yshp%6nmab%(v+7mr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # DRF
    'rest_framework',
    # Internal apps
    'monitor_trafico',
    'monitor_servicios',
    'generador_reportes.apps.GeneradorReportesConfig',
    'recolector_inventarios',
    'api_gateway',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Monitor de Tráfico — registra y evalúa cada request (Rate Limiting / DoS)
    'monitor_trafico.middleware.TrafficMonitorMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# =============================================================================
# DATABASES - Persistencia Políglota
# =============================================================================

# --- PostgreSQL (Datos Relacionales y Financieros) ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bite_db',
        'USER': 'bite_user',
        'PASSWORD': 'Bite_KISS_2026!',
        'HOST': '100.31.110.6',  
        'PORT': '5432',
    }
}

# --- MongoDB (Datos Documentales y Telemetría) ---
# URI de conexión para tu MongoConnector (usando PyMongo o Motor)
MONGO_URI = "mongodb://bite_mongo_user:Mongo_KISS_2026!@100.31.110.6:27017/bite_telemetry?authSource=bite_telemetry"
MONGO_DB_NAME = "bite_telemetry"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# =============================================================================
# EXPERIMENTO ASR DE DISPONIBILIDAD — Heartbeat + Active Redundancy
# =============================================================================

# Instancias lógicas del Generador de Reportes que participan en el experimento.
# En AWS, cada nombre correspondería a una instancia EC2/ECS diferente.
REPORT_GENERATOR_INSTANCES = [
    'generador_reportes_1',
    'generador_reportes_2',
]

# Frecuencia de envío de heartbeats (segundos).
# Con 0.2 s de intervalo y umbral de 0.8 s → detección garantizada < 1 s (ASR1).
HEARTBEAT_INTERVAL_SECONDS = 0.2

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'