# Generated by Django 6.0.5 on 2026-05-06 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id_business', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'businesses',
            },
        ),
        migrations.CreateModel(
            name='CloudGovernance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory_tags', models.JSONField(default=dict)),
                ('responsible_area', models.CharField(max_length=255)),
                ('spend_limits_by_project', models.JSONField(default=dict)),
                ('id_business', models.OneToOneField(db_column='id_business', on_delete=django.db.models.deletion.CASCADE, related_name='governance', to='recolector_inventarios.business')),
            ],
            options={
                'db_table': 'cloud_governance',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=7)),
                ('total_usd_spent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('assigned_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('overdue', 'Vencido')], default='pending', max_length=20)),
                ('id_business', models.ForeignKey(db_column='id_business', on_delete=django.db.models.deletion.CASCADE, related_name='consumption_summaries', to='recolector_inventarios.business')),
            ],
            options={
                'db_table': 'consumption_summary',
                'unique_together': {('id_business', 'month_year')},
            },
        ),
    ]